### ISSUE TITLE
Loadout manager doesn't work on dedicated

### ISSUE THREAD

**Issue by abramsba** [SpyderBlack723/SpyderAddons#13]
I last updated on the steam workshop on 17.08.2016, I had also copied this version over to my dedicated server. When I test a mission using the loadout manager synced to an object on single-player and listen multiplayer it works fine, but on dedicated multiplayer the loadout manager isn't avaliable on the object. 

The setup is a basic ammo container sycned up to the loadout manager module.

**Comment by DavisBrown723** [comment]
Please test with this build

https://www.dropbox.com/s/jqljjo8qq5962ch/SpyderAddons_20160827.zip?dl=0

**Comment by abramsba** [comment]
Sorry, just came back from vacation. I get a 404 with that URL. 

EDIT: Just tried with the workshop version, loadout manager is working again. Thanks!
