### ISSUE TITLE
Spawned Vehicles - Engine won't start

### ISSUE THREAD

**Issue by Condas** [SpyderBlack723/SpyderAddons#14]
A handful of both modded and NATO vehicles I have tried do not allow you to start the engines once they are spawned from the Vehicle Spawner module.

A few examples:
HMMWVs from Uparmored HMMWVs, RHS, and CUPs
Hunters (M-ATV) Unarmed, HMG, GMG

**Comment by DavisBrown723** [comment]
Seems to be completely random - some work, some don't.

Notes:
- Unrelated to spawn height
- Appears more likely to occur with certain vehicle classes
- engineOn command fails to turn on the engine

Solution: Spawn the vehicle repeatedly until the engine work correctly

Not even sure if bug is related to SpyderAddons at all.. weirdest thing I've seen in awhile.

**Comment by nateberkopec** [comment]
Can repro.

**Comment by nateberkopec** [comment]
Haven't tested, but this looks superficially similar to https://forums.bistudio.com/topic/190727-solved-cant-turn-engine-on-after-spawning-an-empty-vehicle-maybe-a-bug/

**Comment by DavisBrown723** [comment]
Probably is considering it takes place around the same time the bug was introduced (1.6X)

**Comment by DavisBrown723** [comment]
Fixed with the next release.
