### ISSUE TITLE
Update repo?

### ISSUE THREAD

**Issue by nateberkopec** [SpyderBlack723/SpyderAddons#15]
Would love to take a closer look in here, but it looks like the Github version isn't the one currently released on Steam?

**Comment by DavisBrown723** [comment]
If you actually want to contribute I can update it, otherwise just download
off BIF and unpbo it.

**Comment by nateberkopec** [comment]
Tell you what, I'll give you a PR to fix this vehicle spawning issue, and then you can push the updated master :D

**Comment by DavisBrown723** [comment]
Hold off because my local is probably newer for that component.

**Comment by SpyderBlack723** [comment]
For that conponent

**Comment by DavisBrown723** [comment]
Note for anyone who crosses this issue:

Keep in mind that I have no real interesting in furthering the development of this mod until A4 so even with an updated repo, I'll basically just be fixing any issues that crop up (and accepting appropriate PR's).

**Comment by DavisBrown723** [comment]
Done (I've also fixed the vehicle issue)

**Comment by nateberkopec** [comment]
Thanks!
