### ISSUE TITLE
Differ between enemies and neutral faction disguises

### ISSUE THREAD

**Issue by xetra11** [SpyderBlack723/SpyderAddons#18]
I had a situation where I was able to steal the truck in front of an enemy roadblock. I was disguised as a civilian and setup everything for the whitelisting to civilian clothing.

There should be a difference between neutral and hostile factions.

Neutrals should be able to pass by hostile militants but not be able to use their stuff or come too close to them.

Hostile disguises should make it possible to do a lot more stuff. Like coming pretty close. But not too close because the enemy should be able to realise ur not one of them after a while

**Comment by DavisBrown723** [comment]
The incognito module should be considered obsolete, use incontinentia's incognito script instead.
