### ISSUE TITLE
Is RECOMPILE really needed?

### ISSUE THREAD

**Issue by dixonbegay** [SpyderBlack723/SpyderAddons#5]
Is there any reason recompiling all of your functions is needed? I think all of your data is saved currently on a per mission basis in arrays? I ask because recompiling functions contributes to long load times, so having the least amount of functions that need to be recompiled, the better.

**Comment by DavisBrown723** [comment]
recompile is needed to use filePatching properly for dev use. That's why there is a RECOMPILE macro in the main component, it just needs to be toggled to 0 at release

EDIT: OT but added you as collaborator.

**Comment by DavisBrown723** [comment]
any recompile = 1/0 should be changed to recompile = RECOMPILE

**Comment by dixonbegay** [comment]
Ah ok that's what you're using it for. I just want to make sure. I have been using the version on GitHub lately and haven't actually messed around with the stable version, so I didn't know when you released you changed the macro RECOMPILE to 0.

**Comment by DavisBrown723** [comment]
Tbh, I don't think I did.. but that's what it is for ;)
