### ISSUE TITLE
[Optimization] 1.55: Utilize incoming scripting command improvements for all modules

### ISSUE THREAD

**Issue by DavisBrown723** [SpyderBlack723/SpyderAddons#8]
Update 1.55 will be bringing many new scripting commands to replace/improve upon existing commands/functions.

Can currently improve existing module code:
selectRandom: https://community.bistudio.com/wiki/selectRandom
pushBackUnique: https://community.bistudio.com/wiki/pushBackUnique
getRelDir: https://community.bistudio.com/wiki/getRelDir
getRelPos: https://community.bistudio.com/wiki/getRelPos

**Comment by dixonbegay** [comment]
pushBackUnique - is this to make sure that all the elements are the same 'typeName'?

**Comment by DavisBrown723** [comment]
It ensures that the value you are adding to the array is unique to that array

ex.

[1,2,3] pushBackUnique 4 // Works
[1,2,3] pushBackUnique 3 // Fails

**Comment by DavisBrown723** [comment]
Done
613ea45
93f1bb4

**Comment by dixonbegay** [comment]
FYI... These commands haven't been implemented for Linux users yet. Linux users are still on 1.54 as of couple days ago. Haven't heard of update for Linux since then.
